# Generated by Django 5.0.4 on 2024-04-27 21:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(default='Community Name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(default='uploads/service_pictures/default.png', upload_to='uploads/service_pictures/')),
                ('location', models.CharField(default='410255493', max_length=150)),
                ('is_private', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(related_name='followed_communities', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(related_name='managed_communities', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(blank=True, null=True)),
                ('hasRead', models.BooleanField(default=False)),
                ('offerType', models.TextField(blank=True, null=True)),
                ('offerPk', models.IntegerField(default=0)),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
