# Generated by Django 4.2.1 on 2024-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0002_remove_community_category_alter_community_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='location',
            field=models.CharField(default='41.0255493,28.9742571,7', max_length=100),
        ),
    ]
