# Generated by Django 5.0.4 on 2024-04-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='posts',
            field=models.ManyToManyField(related_name='communities', to='socio.post'),
        ),
    ]
