# Generated by Django 4.2.1 on 2024-04-20 16:30

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0004_alter_community_location_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='location',
            field=models.CharField(default='410255493', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='41.0255493,28.9742571', max_length=63),
        ),
    ]
