# Generated by Django 5.0.4 on 2024-05-02 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0004_rename_dislikers_post_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='posts', to='socio.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='communit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.community'),
        ),
        migrations.CreateModel(
            name='PictureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='picture_sections')),
                ('specialized_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.specializedpost')),
            ],
        ),
    ]
