# Generated by Django 4.2.1 on 2024-04-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0005_alter_community_location_alter_userprofile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
