# Generated by Django 5.0.4 on 2024-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0006_remove_specializedpost_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.CharField(default='410255493', max_length=150),
        ),
    ]
