# Generated by Django 5.0.4 on 2024-05-04 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0007_community_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('post_type', models.CharField(choices=[('IMAGE', 'image'), ('TEXT', 'text'), ('VIDEO', 'video'), ('AUDIO', 'audio'), ('DATETIME', 'datetime'), ('LOCATION', 'location')], max_length=20)),
                ('mandatory', models.BooleanField(default=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='410255493', max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('invite', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.community')),
                ('fields', models.ManyToManyField(related_name='post_templates', to='socio.posttemplateitem')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.posttemplate'),
        ),
        migrations.AddField(
            model_name='post',
            name='fields',
            field=models.ManyToManyField(related_name='posts', to='socio.posttemplateitem'),
        ),
    ]
