# Generated by Django 5.0.4 on 2024-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0008_posttemplateitem_remove_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplateitem',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
