# Generated by Django 5.0.4 on 2024-05-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0009_alter_posttemplateitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplateitem',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/post_audio/'),
        ),
        migrations.AlterField(
            model_name='posttemplateitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_pictures/'),
        ),
        migrations.AlterField(
            model_name='posttemplateitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/post_video/'),
        ),
    ]
