# Generated by Django 5.0.4 on 2024-05-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
