# Generated by Django 5.0.4 on 2024-05-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0012_remove_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='posts', to='socio.comment'),
        ),
    ]
