services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=localhost
      - DB_NAME=Socio
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_PORT=5432
    
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=commansys
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
